cart/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [

    url(r'CartAdd/(\d+)', CartAdd, name='CartAdd'),
    url(r'details/$', CartDetail, name='CartDetail'),
    url(r'remove/(?P<product_id>\d+)/$', CartRemove, name='CartRemove'),

    url(r'^$', CartDetail, name='CartDetail')
]

simple_shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from shop.views import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^contacts/thanks/$', thanks, name='thanks'),
    url(r'^contacts/$', contacts, name='contacts'),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^$', index, name='index'),
    url(r'^sale/$', sale, name='sale'),
    url(r'^cart_adding/', include('orders.urls')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^user/', include('userManagementApp.urls', namespace='user'))

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

cart/models.py
from django.db import models


# Create your models here.
class Product(models.Model):
    sku = models.CharField(max_length=50)
    price = models.DecimalField(decimal_places=2, max_digits=10)


class CartItem(models.Model):
    cart = models.ForeignKey('Cart', null=True, blank=True)
    item = models.ForeignKey(Product)
    quantity = models.PositiveIntegerField(default=1)
    item_total_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)


class Cart(models.Model):
    total = models.DecimalField(max_digits=100, decimal_places=2, default=0.00)

cart/forms.py
from django import forms
from .models import *

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)


class ProductsForm(forms.Form):
    products = forms.ModelChoiceField(label=u'Products', queryset=Product.objects.all())

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from django.http import Http404, JsonResponse
from django.template import loader
from django.template.context_processors import csrf


def details(request):
    products = Product.objects.all()
    title = 'Корзина'
    return render(request, 'cart/details.html', {'title': title,
                                                 'products': products})


@require_POST
def CartAdd(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:CartDetail')


def CartRemove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:CartDetail')


def CartDetail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={
                'quantity': item['quantity'],
                'update': True
            })

    return render(request, 'cart/details.html', {'cart': cart})


def get_cart_form(request, product_id):
    """ Заполняет форму
    """
    if request.is_ajax():
        cart_form = CartAddProductForm
        context = {'form': cart_form, 'id': product_id}
        context.update(csrf(request))
        html = loader.render_to_string('cart/details.html', context)
        data = {'errors': False, 'html': html}
        return JsonResponse(data)
    raise Http404

cart/templates/cart/base_cart.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="ru">
<!-- HEAD -->
<head>
    <meta charset="UTF-8">

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/toggle_cart.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <title></title>
</head>
<!-- END HEAD -->
<!-- BODY -->
<body>
<div class="container_top">
    <div class="row">
        <div class="panel_top_menu col-xs-12">
            <div class="top_menu col-md-9">
                {% block menu %}
                {% include 'inc/inc-menu.html' %}
                {% endblock %}
            </div>
    <!--CART-->
        </div>
    </div>
    <div class="clear"></div>
</div>
<div class="container">
    <div class="row">
                      {% block content %}
                        {% endblock %}
    </div>
</div>
</body>
<!-- END BODY -->

</html>

cart/templates/cart/detail.html
{% extends "base_cart.html" %}

{% load static %}
{% block content %}

  <section id="header">
    <div class="top container">
      Онлайн-Магазин
    </div>
    <div class="top-bl">
      <div class="container">
        <div class="cart">Ваша корзина пуста</div>
      </div>
    </div>
  </section>
  <section id="content row" class="container">
     <h1>Ваша корзина товаров</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Изображение</th>
        <th>Продукт</th>
        <th>Количество</th>
        <th>Удалить</th>
        <th>Полная цена</th>
        <th>Цена</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{{ product.image }}" alt="" />
              </a>
            </td>
            <td>{{ product.name }}</td>
                   <td>
              <form action="{% url 'cart:CartAdd' product.id %}" method="post" class="add">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                {% csrf_token %}
                <input type="submit" value="Обновить">
              </form>
                  </td>
            <td><a href="{% url 'cart:CartRemove' product.id %}">Удалить</a></td>
            <td class="num">{{ item.price }} руб.</td>
            <td class="num">{{ item.total_price }} руб.</td>
          </tr>
        {% endwith %}
      {% endfor %}
        <tr class="total">
          <td>Total</td>
          <td colspan="4"></td>
          <td class="num">{{ cart.get_total_price }} руб.</td>
        </tr>
    </tbody>
  </table>
  <p class="text-right">

    <a href="#">Оформить заказ</a>
  </p>
  </section>
{% block title %}
  Ваша корзина товаров
{% endblock %}

{% endblock %}

cart/templates/cart/details.html
{% load static %}

    <div class="cart_body"><div class="item-list">
        <div class="cart_header text-center" id="cart_header">
            Ваша корзина товаров
        </div>

            <ul class="text-left" >
                {% for product_in_cart in products_in_cart %}
                <br><li>
                 <b>{{ product_in_cart.product.name }}</b> {{ product_in_cart.nmb }} шт.  по {{ product_in_cart.price_per_item }} р.
                    <a class="delete-item" href="" data-product_id="{{ product_in_cart.id }}">x</a>

                </li><br>
                {% endfor %}
            </ul>

        <div class="cart_order text-center">
            <a href="#">Оформить заказ</a>
        </div>
    </div>
 </div>